before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PGDATABASE=CRUDTestDB
  - cd "C:\\Program Files\\PostgreSQL\\9.6\\bin\\"
  - createdb CRUDTestDB
  - psql -q -f C:\\projects\\basiccrudtool3\\Resources\\Chinook_PostgreSql.sql
  - cd C:\\projects\\basiccrudtool3\\Src
  - nuget restore
  
services:
  - postgresql
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: /j7KLdZuSN7ukT698JVqmAVBEYgI4xALwEEInwz8ureU7JmS/Z9IMUWPVRgYoTUc
    
test_script:
 - dotnet test --collect:"XPlat Code Coverage"