before_build:
  - cd Resources
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - C:\\Program Files\\PostgreSQL\\9.6\\bin\\psql.exe
  - \i "Chinook_PostgreSql.sql"
  - SELECT * FROM Album LIMIT 5
  - \q
  - cd ..\Src
  - nuget restore
  
services:
  - postgresql