before_build:
  - cd Resources
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10.1\bin\;%PATH%
  - psql
  - \i "Chinook_PostgreSql.sql"
  - SELECT * FROM Album LIMIT 5
  - \q
  - cd ..\Src
  - nuget restore
  
services:
  - postgresql101